#!/usr/bin/env ruby

container 'hackuman/test'

service 'hello_world' do
  container 'busybox'
  description "Hello World"
  start run: ['bin/sh -c "while true; do echo Hello World; sleep 1; done"']
end

service 'truebox' do
  container 'busybox'
  description 'True box'
  start run: 'bin/bash true'
end
